version: "3"
services:
  magiconion:
    image: magiconion_chatsample:dev
    build:
      context: .
      dockerfile: ChatApp.Server/Dockerfile
    ports:
      - 12345:12345
      - 9184:9184
    environment:
      - MagicOnion__OpenTelemetry__MetricsExporterEndpoint=http://127.0.0.1:9184/metrics/
      - MagicOnion__OpenTelemetry__TracerExporterEndpoint=http://zipkin:9411/api/v2/spans
      - MagicOnion__OpenTelemetry__PrometheusMetricsHostingEndpoint=http://+:9184/metrics/

  prometheus:
    image: prom/prometheus:v2.11.1
    container_name: prometheus
    volumes:
      # persistent prometheus database
      - ./prometheus/data/:/prometheus
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/alert.rules:/etc/prometheus/alert.rules
    ports:
      - "9090:9090"

  # # if you want monitor linux host machine, install node-exporter or use it through container.
  # # settings detail: https://qiita.com/kanga/items/21acb042237f8a27f437
  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   ports:
  #     - 9100:9100
  #   volumes:
  #     - /:/host:ro
  #   net: host
  #   pid: host
  #   command: quay.io/prometheus/node-exporter --path.rootfs /host

  cAdvisor:
    image: google/cadvisor:latest
    container_name: cAdvisor
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      # persistent grafana database
      - ./grafana/:/var/lib/grafana
    ports:
      - 3000:3000

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    command: "--config.file=/etc/alertmanager/config.yml"
    ports:
      - 9093:9093

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
