apiVersion: v1
kind: Service
metadata:
  name: chatapp-svc
spec:
  selector:
    app: magiconion
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 12345
      targetPort: magiconion
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-prometheus-svc
spec:
  selector:
    app: magiconion
  ports:
    - protocol: TCP
      port: 9184
      targetPort: prometheus
