# template: https://github.com/Cysharp/Actions/tree/main/.github/scripts/_template_benchmark_config.yaml
# config2args script: https://github.com/Cysharp/Actions/tree/main/.github/scripts/benchmark_config2args.sh
apt-tools: "libmsquic"
dotnet-version: 8.0
benchmark-expire-min: 15
benchmark-timeout-min: 10
benchmark-client-run-script-path: ".github/scripts/benchmark-client-run.sh"
benchmark-client-run-script-args: '--args "-u http://${BENCHMARK_SERVER_NAME}:5000 --protocol {{ protocol }} -s CI --rounds 3 --channels {{ channels }} --streams {{ streams }} --serialization {{ serialization }} --validate true --tags {{ tags }}"'
benchmark-server-run-script-path: ".github/scripts/benchmark-server-run.sh"
benchmark-server-run-script-args: '--args "-u http://0.0.0.0:5000 --protocol {{ protocol }} --serialization {{ serialization }} --validate true --tags {{ tags }}"'
benchmark-server-stop-script-path: ".github/scripts/benchmark-server-stop.sh"
jobs:
  # h2c
  - tags: legend:memorypack-h3-linux,streams:1x1,protocol:h3,serialization:memorypack
    protocol: h3
    channels: 1
    streams: 1
    serialization: memorypack
  - tags: legend:memorypack-h3-linux,streams:1x28,protocol:h3,serialization:memorypack
    protocol: h3
    channels: 28
    streams: 1
    serialization: memorypack
  - tags: legend:memorypack-h3-linux,streams:70x1,protocol:h3,serialization:memorypack
    protocol: h3
    channels: 1
    streams: 70
    serialization: memorypack
  - tags: legend:memorypack-h3-linux,streams:70x28,protocol:h3,serialization:memorypack
    protocol: h3
    channels: 28
    streams: 70
    serialization: memorypack
