# template: https://github.com/Cysharp/Actions/tree/main/.github/scripts/_template_benchmark_config.yaml
# config2args script: https://github.com/Cysharp/Actions/tree/main/.github/scripts/benchmark_config2args.sh
apt-tools: ""
dotnet-version: 10.0
benchmark-expire-min: 20
benchmark-location: "japaneast"
benchmark-timeout-min: 10
benchmark-client-run-script-path: ".github/scripts/benchmark-client-run.sh"
benchmark-client-run-script-args: '--run-args "-u http://${BENCHMARK_SERVER_NAME}:5000 --protocol {{ protocol }} -s {{ scenario }} --rounds 1 -d 180 --channels {{ channels }} --streams {{ streams }} --serialization {{ serialization }} --validate true --tags {{ tags }}" --build-args "{{ buildArgsClient }}"'
benchmark-server-run-script-path: ".github/scripts/benchmark-server-run.sh"
benchmark-server-run-script-args: '--run-args "-u http://0.0.0.0:5000 --protocol {{ protocol }} --serialization {{ serialization }} --validate true --tags {{ tags }}" --build-args "{{ buildArgsServer }}"'
benchmark-server-stop-script-path: ".github/scripts/benchmark-server-stop.sh"
jobs:
  # h2c (30fps)
  - tags: legend:messagepack-h2c-linux,streams:1x500,protocol:h2c,serialization:messagepack
    protocol: h2c
    channels: 500
    streams: 1
    serialization: messagepack
    scenario: MetaverseBroadcast30Fps
  - tags: legend:messagepack-h2c-linux,streams:1x800,protocol:h2c,serialization:messagepack
    protocol: h2c
    channels: 800
    streams: 1
    serialization: messagepack
    scenario: MetaverseBroadcast30Fps
  - tags: legend:messagepack-h2c-linux,streams:1x1000,protocol:h2c,serialization:messagepack
    protocol: h2c
    channels: 1000
    streams: 1
    serialization: messagepack
    scenario: MetaverseBroadcast30Fps
  # h2c (15fps)
  - tags: legend:messagepack-h2c-linux,streams:1x500,protocol:h2c,serialization:messagepack
    protocol: h2c
    channels: 500
    streams: 1
    serialization: messagepack
    scenario: MetaverseBroadcast15Fps
  - tags: legend:messagepack-h2c-linux,streams:1x800,protocol:h2c,serialization:messagepack
    protocol: h2c
    channels: 800
    streams: 1
    serialization: messagepack
    scenario: MetaverseBroadcast15Fps
  - tags: legend:messagepack-h2c-linux,streams:1x1000,protocol:h2c,serialization:messagepack
    protocol: h2c
    channels: 1000
    streams: 1
    serialization: messagepack
    scenario: MetaverseBroadcast15Fps
  - tags: legend:messagepack-h2c-linux,streams:1x2000,protocol:h2c,serialization:messagepack
    protocol: h2c
    channels: 2000
    streams: 1
    serialization: messagepack
    scenario: MetaverseBroadcast15Fps
