version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
jobs:
  build-test:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build ./src/MagicOnion/ -c Debug
      - run: dotnet build ./src/MagicOnion.Annotation/ -c Debug
      - run: dotnet build ./src/MagicOnion.Hosting/ -c Debug
      - run: dotnet build ./src/MagicOnion.HttpGateway/ -c Debug
      - run: dotnet build ./src/MagicOnion.Redis/ -c Debug
      - run: dotnet build ./src/MagicOnion.UniversalCodeGenerator/ -c Debug
      - run: dotnet test ./tests/MagicOnion.NetCoreTests/ -c Debug
      - run: dotnet test ./tests/MagicOnion.Hosting.Tests/ -c Debug
  build-push:
    executor: dotnet
    steps:
      - checkout
      # - run: dotnet build -c Release -p:Version=${CIRCLE_TAG}
      # - run: dotnet test -c Release --no-build
      # - run: dotnet pack ./src/MicroBatchFramework/MicroBatchFramework.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      # - run: dotnet pack ./src/MicroBatchFramework.WebHosting/MicroBatchFramework.WebHosting.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      # - store_artifacts:
      #     path: ./src/MicroBatchFramework/bin/Release
      #     destination: ./MicroBatchFramework/
      # - store_artifacts:
      #     path: ./src/MicroBatchFramework.WebHosting/bin/Release
      #     destination: ./MicroBatchFramework.WebHosting/
      # - run: dotnet nuget push ./src/MicroBatchFramework/bin/Release/MicroBatchFramework.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
      # - run: dotnet nuget push ./src/MicroBatchFramework.WebHosting/bin/Release/MicroBatchFramework.WebHosting.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
workflows:
  version: 2
  build-and-push:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - build-push:
          filters:
            tags:
              only: /^\d\.\d\.\d.*/
            branches:
              ignore: /.*/
