name: Benchmark

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
    inputs:
      reuse:
        description: "reuse: Reuse existing benchmark server if possible"
        required: false
        default: true
        type: boolean
      reuse_runid:
        description: "reuse_runid: Use this run id for benchmark name for reuse"
        required: false
        type: string
        default: "wf"
      benchmark-config-name:
        description: "benchmark-config-name: Select benchmark config name"
        required: false
        default: workflow_dispatch_messagepack_h2c
        type: choice
        options:
          - workflow_dispatch_broadcast
          - workflow_dispatch_memorypack_h2
          - workflow_dispatch_memorypack_h2c
          - workflow_dispatch_memorypack_h3
          - workflow_dispatch_messagepack_h2
          - workflow_dispatch_messagepack_h2c
          - workflow_dispatch_messagepack_h3
          - workflow_dispatch_messagepack_h2c_eastus
          - workflow_dispatch_messagepack_h2_nugetclient
          - workflow_dispatch_messagepack_h2_nugetserver
          - workflow_dispatch_messagepack_h2c_nugetclient
          - workflow_dispatch_messagepack_h2c_nugetserver
          - workflow_dispatch_messagepack_h3_nugetclient
          - workflow_dispatch_messagepack_h3_nugetserver
          - workflow_dispatch_messagepack_h2c_serverstreaming
          - issue
          - schedule_weekly
          - schedule

jobs:
  loader:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: Cysharp/Actions/.github/workflows/benchmark-loader.yaml@main
    with:
      benchmark-name-prefix: "magiconion-${{ github.event.issue.number || (inputs.reuse && inputs.reuse_runid || github.run_number) }}"
      benchmark-config-path: "perf/BenchmarkApp/configs/${{ inputs.benchmark-config-name || github.event_name }}.yaml"
    secrets: inherit

  benchmark:
    needs: [loader]
    if: ${{ needs.loader.outputs.is-benchmarkable }}
    permissions:
      actions: read
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    strategy:
      max-parallel: 3 # 3 parallel max
      fail-fast: false # no care about other benchmark
      matrix: ${{ fromJson(needs.loader.outputs.matrix) }}
    uses: Cysharp/Actions/.github/workflows/benchmark-execute.yaml@main
    with:
      benchmark-name: "${{ matrix.benchmarkName }}"
      benchmark-config-path: "${{ matrix.config }}"
      branch: "${{ matrix.branch }}"
    secrets: inherit

  # cleanup-failed:
  #   if: ${{ failure() || success() }}
  #   needs: [benchmark]
  #   permissions:
  #     actions: read
  #     contents: read
  #     id-token: write
  #     issues: write
  #     pull-requests: write
  #   uses: Cysharp/Actions/.github/workflows/benchmark-cleanup.yaml@main
  #   secrets: inherit

  actions-timeline:
    needs: [loader, benchmark, cleanup-failed]
    permissions:
      contents: read
    uses: Cysharp/Actions/.github/workflows/actions-timeline.yaml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
